/** Generated by scripts/gen_theme_registry.py from fastlanelabs_sdk/theme_registry.py. Do not edit.
 *  Shared by core's tailwind.config.js and build-app.mjs: `presets: [preset]`.
 *  Every var() carries its literal default so a build made with this preset still
 *  renders on a host that predates the generated defaults. */
export default {
  "theme": {
    "extend": {
      "colors": {
        "ink": {
          "50": "rgb(var(--fl-ink-50) / <alpha-value>)",
          "100": "rgb(var(--fl-ink-100) / <alpha-value>)",
          "200": "rgb(var(--fl-ink-200) / <alpha-value>)",
          "300": "rgb(var(--fl-ink-300) / <alpha-value>)",
          "400": "rgb(var(--fl-ink-400) / <alpha-value>)",
          "500": "rgb(var(--fl-ink-500) / <alpha-value>)",
          "600": "rgb(var(--fl-ink-600) / <alpha-value>)",
          "700": "rgb(var(--fl-ink-700) / <alpha-value>)",
          "800": "rgb(var(--fl-ink-800) / <alpha-value>)",
          "900": "rgb(var(--fl-ink-900) / <alpha-value>)",
          "950": "rgb(var(--fl-ink-950) / <alpha-value>)"
        },
        "accent": {
          "50": "rgb(var(--fl-accent-50) / <alpha-value>)",
          "100": "rgb(var(--fl-accent-100) / <alpha-value>)",
          "200": "rgb(var(--fl-accent-200) / <alpha-value>)",
          "300": "rgb(var(--fl-accent-300) / <alpha-value>)",
          "400": "rgb(var(--fl-accent-400) / <alpha-value>)",
          "500": "rgb(var(--fl-accent-500) / <alpha-value>)",
          "600": "rgb(var(--fl-accent-600) / <alpha-value>)",
          "700": "rgb(var(--fl-accent-700) / <alpha-value>)",
          "800": "rgb(var(--fl-accent-800) / <alpha-value>)",
          "900": "rgb(var(--fl-accent-900) / <alpha-value>)",
          "950": "rgb(var(--fl-accent-950) / <alpha-value>)"
        },
        "success": {
          "50": "rgb(var(--fl-success-50, 236 253 245) / <alpha-value>)",
          "100": "rgb(var(--fl-success-100, 209 250 229) / <alpha-value>)",
          "200": "rgb(var(--fl-success-200, 167 243 208) / <alpha-value>)",
          "300": "rgb(var(--fl-success-300, 110 231 183) / <alpha-value>)",
          "400": "rgb(var(--fl-success-400, 52 211 153) / <alpha-value>)",
          "500": "rgb(var(--fl-success-500, 16 185 129) / <alpha-value>)",
          "600": "rgb(var(--fl-success-600, 5 150 105) / <alpha-value>)",
          "700": "rgb(var(--fl-success-700, 4 120 87) / <alpha-value>)",
          "800": "rgb(var(--fl-success-800, 6 95 70) / <alpha-value>)",
          "900": "rgb(var(--fl-success-900, 6 78 59) / <alpha-value>)",
          "950": "rgb(var(--fl-success-950, 2 44 34) / <alpha-value>)",
          "solid": "rgb(var(--fl-success-solid, 5 150 105) / <alpha-value>)",
          "soft": "rgb(var(--fl-success-soft, 236 253 245) / <alpha-value>)",
          "border": "rgb(var(--fl-success-border, 167 243 208) / <alpha-value>)",
          "text": "rgb(var(--fl-success-text, 4 120 87) / <alpha-value>)",
          "strong": "rgb(var(--fl-success-strong, 6 78 59) / <alpha-value>)"
        },
        "emerald": {
          "50": "rgb(var(--fl-success-50, 236 253 245) / <alpha-value>)",
          "100": "rgb(var(--fl-success-100, 209 250 229) / <alpha-value>)",
          "200": "rgb(var(--fl-success-200, 167 243 208) / <alpha-value>)",
          "300": "rgb(var(--fl-success-300, 110 231 183) / <alpha-value>)",
          "400": "rgb(var(--fl-success-400, 52 211 153) / <alpha-value>)",
          "500": "rgb(var(--fl-success-500, 16 185 129) / <alpha-value>)",
          "600": "rgb(var(--fl-success-600, 5 150 105) / <alpha-value>)",
          "700": "rgb(var(--fl-success-700, 4 120 87) / <alpha-value>)",
          "800": "rgb(var(--fl-success-800, 6 95 70) / <alpha-value>)",
          "900": "rgb(var(--fl-success-900, 6 78 59) / <alpha-value>)",
          "950": "rgb(var(--fl-success-950, 2 44 34) / <alpha-value>)"
        },
        "warning": {
          "50": "rgb(var(--fl-warning-50, 255 251 235) / <alpha-value>)",
          "100": "rgb(var(--fl-warning-100, 254 243 199) / <alpha-value>)",
          "200": "rgb(var(--fl-warning-200, 253 230 138) / <alpha-value>)",
          "300": "rgb(var(--fl-warning-300, 252 211 77) / <alpha-value>)",
          "400": "rgb(var(--fl-warning-400, 251 191 36) / <alpha-value>)",
          "500": "rgb(var(--fl-warning-500, 245 158 11) / <alpha-value>)",
          "600": "rgb(var(--fl-warning-600, 217 119 6) / <alpha-value>)",
          "700": "rgb(var(--fl-warning-700, 180 83 9) / <alpha-value>)",
          "800": "rgb(var(--fl-warning-800, 146 64 14) / <alpha-value>)",
          "900": "rgb(var(--fl-warning-900, 120 53 15) / <alpha-value>)",
          "950": "rgb(var(--fl-warning-950, 69 26 3) / <alpha-value>)",
          "solid": "rgb(var(--fl-warning-solid, 217 119 6) / <alpha-value>)",
          "soft": "rgb(var(--fl-warning-soft, 255 251 235) / <alpha-value>)",
          "border": "rgb(var(--fl-warning-border, 253 230 138) / <alpha-value>)",
          "text": "rgb(var(--fl-warning-text, 180 83 9) / <alpha-value>)",
          "strong": "rgb(var(--fl-warning-strong, 120 53 15) / <alpha-value>)"
        },
        "amber": {
          "50": "rgb(var(--fl-warning-50, 255 251 235) / <alpha-value>)",
          "100": "rgb(var(--fl-warning-100, 254 243 199) / <alpha-value>)",
          "200": "rgb(var(--fl-warning-200, 253 230 138) / <alpha-value>)",
          "300": "rgb(var(--fl-warning-300, 252 211 77) / <alpha-value>)",
          "400": "rgb(var(--fl-warning-400, 251 191 36) / <alpha-value>)",
          "500": "rgb(var(--fl-warning-500, 245 158 11) / <alpha-value>)",
          "600": "rgb(var(--fl-warning-600, 217 119 6) / <alpha-value>)",
          "700": "rgb(var(--fl-warning-700, 180 83 9) / <alpha-value>)",
          "800": "rgb(var(--fl-warning-800, 146 64 14) / <alpha-value>)",
          "900": "rgb(var(--fl-warning-900, 120 53 15) / <alpha-value>)",
          "950": "rgb(var(--fl-warning-950, 69 26 3) / <alpha-value>)"
        },
        "danger": {
          "50": "rgb(var(--fl-danger-50, 254 242 242) / <alpha-value>)",
          "100": "rgb(var(--fl-danger-100, 254 226 226) / <alpha-value>)",
          "200": "rgb(var(--fl-danger-200, 254 202 202) / <alpha-value>)",
          "300": "rgb(var(--fl-danger-300, 252 165 165) / <alpha-value>)",
          "400": "rgb(var(--fl-danger-400, 248 113 113) / <alpha-value>)",
          "500": "rgb(var(--fl-danger-500, 239 68 68) / <alpha-value>)",
          "600": "rgb(var(--fl-danger-600, 220 38 38) / <alpha-value>)",
          "700": "rgb(var(--fl-danger-700, 185 28 28) / <alpha-value>)",
          "800": "rgb(var(--fl-danger-800, 153 27 27) / <alpha-value>)",
          "900": "rgb(var(--fl-danger-900, 127 29 29) / <alpha-value>)",
          "950": "rgb(var(--fl-danger-950, 69 10 10) / <alpha-value>)",
          "solid": "rgb(var(--fl-danger-solid, 220 38 38) / <alpha-value>)",
          "soft": "rgb(var(--fl-danger-soft, 254 242 242) / <alpha-value>)",
          "border": "rgb(var(--fl-danger-border, 254 202 202) / <alpha-value>)",
          "text": "rgb(var(--fl-danger-text, 185 28 28) / <alpha-value>)",
          "strong": "rgb(var(--fl-danger-strong, 127 29 29) / <alpha-value>)"
        },
        "red": {
          "50": "rgb(var(--fl-danger-50, 254 242 242) / <alpha-value>)",
          "100": "rgb(var(--fl-danger-100, 254 226 226) / <alpha-value>)",
          "200": "rgb(var(--fl-danger-200, 254 202 202) / <alpha-value>)",
          "300": "rgb(var(--fl-danger-300, 252 165 165) / <alpha-value>)",
          "400": "rgb(var(--fl-danger-400, 248 113 113) / <alpha-value>)",
          "500": "rgb(var(--fl-danger-500, 239 68 68) / <alpha-value>)",
          "600": "rgb(var(--fl-danger-600, 220 38 38) / <alpha-value>)",
          "700": "rgb(var(--fl-danger-700, 185 28 28) / <alpha-value>)",
          "800": "rgb(var(--fl-danger-800, 153 27 27) / <alpha-value>)",
          "900": "rgb(var(--fl-danger-900, 127 29 29) / <alpha-value>)",
          "950": "rgb(var(--fl-danger-950, 69 10 10) / <alpha-value>)"
        },
        "info": {
          "50": "rgb(var(--fl-info-50, 240 249 255) / <alpha-value>)",
          "100": "rgb(var(--fl-info-100, 224 242 254) / <alpha-value>)",
          "200": "rgb(var(--fl-info-200, 186 230 253) / <alpha-value>)",
          "300": "rgb(var(--fl-info-300, 125 211 252) / <alpha-value>)",
          "400": "rgb(var(--fl-info-400, 56 189 248) / <alpha-value>)",
          "500": "rgb(var(--fl-info-500, 14 165 233) / <alpha-value>)",
          "600": "rgb(var(--fl-info-600, 2 132 199) / <alpha-value>)",
          "700": "rgb(var(--fl-info-700, 3 105 161) / <alpha-value>)",
          "800": "rgb(var(--fl-info-800, 7 89 133) / <alpha-value>)",
          "900": "rgb(var(--fl-info-900, 12 74 110) / <alpha-value>)",
          "950": "rgb(var(--fl-info-950, 8 47 73) / <alpha-value>)",
          "solid": "rgb(var(--fl-info-solid, 2 132 199) / <alpha-value>)",
          "soft": "rgb(var(--fl-info-soft, 240 249 255) / <alpha-value>)",
          "border": "rgb(var(--fl-info-border, 186 230 253) / <alpha-value>)",
          "text": "rgb(var(--fl-info-text, 3 105 161) / <alpha-value>)",
          "strong": "rgb(var(--fl-info-strong, 12 74 110) / <alpha-value>)"
        },
        "sky": {
          "50": "rgb(var(--fl-info-50, 240 249 255) / <alpha-value>)",
          "100": "rgb(var(--fl-info-100, 224 242 254) / <alpha-value>)",
          "200": "rgb(var(--fl-info-200, 186 230 253) / <alpha-value>)",
          "300": "rgb(var(--fl-info-300, 125 211 252) / <alpha-value>)",
          "400": "rgb(var(--fl-info-400, 56 189 248) / <alpha-value>)",
          "500": "rgb(var(--fl-info-500, 14 165 233) / <alpha-value>)",
          "600": "rgb(var(--fl-info-600, 2 132 199) / <alpha-value>)",
          "700": "rgb(var(--fl-info-700, 3 105 161) / <alpha-value>)",
          "800": "rgb(var(--fl-info-800, 7 89 133) / <alpha-value>)",
          "900": "rgb(var(--fl-info-900, 12 74 110) / <alpha-value>)",
          "950": "rgb(var(--fl-info-950, 8 47 73) / <alpha-value>)"
        },
        "page": "rgb(var(--fl-surface-page, 247 247 248) / <alpha-value>)",
        "sunken": "rgb(var(--fl-surface-sunken, 236 236 238) / <alpha-value>)",
        "inverse": "rgb(var(--fl-surface-inverse, 16 17 23) / <alpha-value>)",
        "fg": "rgb(var(--fl-text, 26 27 33) / <alpha-value>)",
        "fg-muted": "rgb(var(--fl-text-muted, 85 87 100) / <alpha-value>)",
        "fg-subtle": "rgb(var(--fl-text-subtle, 108 111 125) / <alpha-value>)",
        "line": "rgb(var(--fl-border, 217 218 222) / <alpha-value>)",
        "line-strong": "rgb(var(--fl-border-strong, 184 186 194) / <alpha-value>)",
        "primary": {
          "DEFAULT": "rgb(var(--fl-primary, 33 72 216) / <alpha-value>)",
          "hover": "rgb(var(--fl-primary-hover, 28 57 174) / <alpha-value>)",
          "soft": "rgb(var(--fl-primary-soft, 238 244 255) / <alpha-value>)"
        }
      },
      "backgroundColor": {
        "white": "rgb(var(--fl-surface) / <alpha-value>)"
      },
      "textColor": {
        "white": "rgb(var(--fl-on-primary) / <alpha-value>)"
      },
      "fontFamily": {
        "sans": [
          "var(--fl-font-sans, Inter)",
          "ui-sans-serif",
          "system-ui"
        ],
        "mono": [
          "var(--fl-font-mono, ui-monospace)",
          "monospace"
        ],
        "display": [
          "var(--fl-font-display, Inter)",
          "ui-sans-serif",
          "system-ui"
        ]
      },
      "fontSize": {
        "fl-2xs": "calc(var(--fl-size-2xs, 10px) * var(--fl-size-scale, 1))",
        "fl-2xs-h": "calc(var(--fl-size-2xs, 10px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-xs": "calc(var(--fl-size-xs, 11px) * var(--fl-size-scale, 1))",
        "fl-xs-h": "calc(var(--fl-size-xs, 11px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-sm": "calc(var(--fl-size-sm, 12px) * var(--fl-size-scale, 1))",
        "fl-sm-h": "calc(var(--fl-size-sm, 12px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-md": "calc(var(--fl-size-md, 13px) * var(--fl-size-scale, 1))",
        "fl-md-h": "calc(var(--fl-size-md, 13px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-base": "calc(var(--fl-size-base, 14px) * var(--fl-size-scale, 1))",
        "fl-base-h": "calc(var(--fl-size-base, 14px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-lg": "calc(var(--fl-size-lg, 15px) * var(--fl-size-scale, 1))",
        "fl-lg-h": "calc(var(--fl-size-lg, 15px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-xl": "calc(var(--fl-size-xl, 16px) * var(--fl-size-scale, 1))",
        "fl-xl-h": "calc(var(--fl-size-xl, 16px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-2xl": "calc(var(--fl-size-2xl, 17px) * var(--fl-size-scale, 1))",
        "fl-2xl-h": "calc(var(--fl-size-2xl, 17px) * var(--fl-size-scale, 1) + 0.5px)",
        "fl-3xl": "calc(var(--fl-size-3xl, 26px) * var(--fl-size-scale, 1))",
        "fl-3xl-h": "calc(var(--fl-size-3xl, 26px) * var(--fl-size-scale, 1) + 0.5px)",
        "xs": [
          "calc(0.75rem * var(--fl-size-scale, 1))",
          {
            "lineHeight": "1rem"
          }
        ],
        "sm": [
          "calc(0.875rem * var(--fl-size-scale, 1))",
          {
            "lineHeight": "1.25rem"
          }
        ],
        "base": [
          "calc(1rem * var(--fl-size-scale, 1))",
          {
            "lineHeight": "1.5rem"
          }
        ],
        "lg": [
          "calc(1.125rem * var(--fl-size-scale, 1))",
          {
            "lineHeight": "1.75rem"
          }
        ],
        "xl": [
          "calc(1.25rem * var(--fl-size-scale, 1))",
          {
            "lineHeight": "1.75rem"
          }
        ],
        "2xl": [
          "calc(1.5rem * var(--fl-size-scale, 1))",
          {
            "lineHeight": "2rem"
          }
        ]
      },
      "fontWeight": {
        "regular": "var(--fl-weight-regular, 400)",
        "medium": "var(--fl-weight-medium, 500)",
        "semibold": "var(--fl-weight-semibold, 600)",
        "bold": "var(--fl-weight-bold, 700)"
      },
      "lineHeight": {
        "fl-tight": "var(--fl-leading-tight, 1.25)",
        "fl-normal": "var(--fl-leading-normal, 1.5)",
        "fl-relaxed": "var(--fl-leading-relaxed, 1.72)"
      },
      "letterSpacing": {
        "fl-tight": "var(--fl-tracking-tight, -0.01em)",
        "fl-normal": "var(--fl-tracking-normal, 0)",
        "fl-wide": "var(--fl-tracking-wide, 0.04em)"
      },
      "spacing": {
        "fl-xs": "calc(var(--fl-space-xs, 4px) * var(--fl-density, 1))",
        "fl-sm": "calc(var(--fl-space-sm, 8px) * var(--fl-density, 1))",
        "fl-md": "calc(var(--fl-space-md, 12px) * var(--fl-density, 1))",
        "fl-lg": "calc(var(--fl-space-lg, 16px) * var(--fl-density, 1))",
        "fl-xl": "calc(var(--fl-space-xl, 24px) * var(--fl-density, 1))",
        "fl-2xl": "calc(var(--fl-space-2xl, 32px) * var(--fl-density, 1))"
      },
      "borderRadius": {
        "sm": "var(--fl-radius-sm, 2px)",
        "DEFAULT": "var(--fl-radius-default, 4px)",
        "md": "var(--fl-radius-md, 6px)",
        "lg": "var(--fl-radius, 8px)",
        "xl": "calc(var(--fl-radius, 8px) * 1.5)",
        "2xl": "calc(var(--fl-radius, 8px) * 2)",
        "pill": "var(--fl-radius-pill, 9999px)"
      },
      "borderWidth": {
        "DEFAULT": "var(--fl-border-width, 1px)",
        "strong": "var(--fl-border-width-strong, 2px)"
      },
      "boxShadow": {
        "sm": "var(--fl-shadow-sm, 0 1px 2px 0 rgba(0,0,0,0.05))",
        "lg": "var(--fl-shadow-lg, 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1))",
        "xl": "var(--fl-shadow-xl, 0 20px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1))",
        "card": "var(--fl-shadow-card, 0 1px 3px 0 rgba(16,17,23,0.06))",
        "popover": "var(--fl-shadow-popover, 0 8px 28px -14px rgba(16,17,23,0.28))",
        "modal": "var(--fl-shadow-modal, 0 24px 70px -20px rgba(16,17,23,0.45))"
      },
      "transitionDuration": {
        "DEFAULT": "var(--fl-duration-base, 150ms)",
        "fast": "var(--fl-duration-fast, 120ms)",
        "base": "var(--fl-duration-base, 150ms)"
      },
      "transitionTimingFunction": {
        "DEFAULT": "var(--fl-ease-standard, cubic-bezier(0.4,0,0.2,1))"
      }
    }
  }
}
