"""Generate every artifact derived from fastlanelabs_sdk/theme_registry.py.

    python scripts/gen_theme_registry.py            # write the files
    python scripts/gen_theme_registry.py --check    # exit 1 if any file is stale

Writes registry_data/theme-registry-v2.json, registry_data/default-theme-v2.json,
frontend/theme-registry.json, frontend/theme-defaults.css, frontend/tailwind-preset.mjs
and docs/theme-v2-tokens.md. Nothing here is hand edited.
"""
from pathlib import Path
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from fastlanelabs_sdk import theme_registry as registry  # noqa: E402
from fastlanelabs_sdk import themes  # noqa: E402

BANNER = "Generated by scripts/gen_theme_registry.py from fastlanelabs_sdk/theme_registry.py. Do not edit."


def triplet(color):
    return " ".join(str(int(color[i:i + 2], 16)) for i in (1, 3, 5))


def css_value(token, text):
    """A token default as a CSS value: refs chain through var(), colors are r g b."""
    match = registry.FALLBACK_EXPR.fullmatch(text)
    if match:
        name, factor, offset = match.groups()
        if token.type == "font-size":
            base = f"var(--fl-fs-{name[len('size-'):]})"
        else:
            base = f"var(--fl-{name})"
        if factor:
            return f"calc({base} * {factor})"
        if offset:
            return f"calc({base} + {offset}px)"
        return base
    if token.type == "color":
        return triplet(text)
    if token.type == "font-size":
        return f"calc({text} * var(--fl-size-scale))"
    return text


def defaults_css():
    lines = [f"/* {BANNER} */",
             ":root, [data-fl-theme-root] {"]
    groups = (("Primitives", registry.PRIMITIVES), ("Semantic roles", registry.SEMANTIC))
    for title, tokens in groups:
        lines.append(f"  /* {title} */")
        for token in tokens:
            lines.append(f"  --fl-{token.name}: {css_value(token, token.default) if token.layer == 'semantic' else (triplet(token.default) if token.type == 'color' else token.default)};")
    lines.append("  /* Effective text sizes: every step follows the scale */")
    lines.extend(f"  --fl-fs-{step}: calc(var(--fl-size-{step}) * var(--fl-size-scale));" for step in registry.SIZE_STEPS)
    lines.append("  --fl-density: 1;")
    lines.append("  /* Component fallbacks: unset tokens follow the live chain; tone-dependent ones are under [data-fl-tone] */")
    for token in registry.COMPONENT_TOKENS:
        if not isinstance(token.default, dict):
            lines.append(f"  --fl-{token.name}: {css_value(token, token.default)};")
    lines.append("}")
    lines.append("[data-density='comfortable'] { --fl-density: 1; }")
    lines.append("[data-density='compact'] { --fl-density: var(--fl-space-compact-factor); }")
    for tone in ("dark", "light"):
        lines.append(f"[data-fl-tone='{tone}'] {{")
        for token in registry.COMPONENT_TOKENS:
            if isinstance(token.default, dict):
                lines.append(f"  --fl-tone-{token.name}: {css_value(token, token.default[tone])};")
        lines.append("}")
    # Platform hue ramps: Tailwind's other palettes, which core and the apps use as decoration. They are
    # not theme tokens; they only follow the colour mode (light is Tailwind's own value, dark the ramp reversed).
    lines.append("/* Platform hue ramps (not theme tokens): light is Tailwind's value, dark the same ramp reversed */")
    lines.append(":root, [data-fl-theme-root] {")
    for hue, ramp in registry.HUE_RAMPS.items():
        lines.extend(f"  --fl-hue-{hue}-{shade}: {triplet(color)};" for shade, color in zip(registry.SHADES, ramp))
    lines.append(f"  --fl-black: {triplet(registry.BLACK_LIGHT)};")
    lines.append("}")
    lines.append("/* A preview that is not dark ends an inherited dark scheme */")
    lines.append("[data-fl-theme-root]:not([data-fl-mode='dark']) { color-scheme: light; }")
    lines.append("/* Dark mode: set by the host from a theme's color scheme and the user's choice, never by tenant text */")
    lines.append("[data-fl-mode='dark'] {")
    lines.append("  color-scheme: dark;")
    for hue, ramp in registry.HUE_RAMPS.items():
        lines.extend(f"  --fl-hue-{hue}-{shade}: {triplet(color)};" for shade, color in zip(registry.SHADES, reversed(ramp)))
    lines.append(f"  --fl-black: {triplet(registry.BLACK_DARK)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def preset():
    shades = registry.SHADES
    default = {t.name: t.default for t in registry.PRIMITIVES}

    def ramp(name, literal=True):
        out = {}
        for shade in shades:
            fallback = f", {triplet(default[f'{name}-{shade}'])}" if literal else ""
            out[str(shade)] = f"rgb(var(--fl-{name}-{shade}{fallback}) / <alpha-value>)"
        return out

    def role(name):
        token = registry.INDEX[name]
        literal = token.default
        while registry.REF.fullmatch(literal):
            literal = registry.INDEX[registry.REF.fullmatch(literal).group(1)].default
        return f"rgb(var(--fl-{name}, {triplet(literal)}) / <alpha-value>)"

    colors = {"ink": ramp("ink", False), "accent": ramp("accent", False)}
    for status, remap in (("success", "emerald"), ("warning", "amber"), ("danger", "red"), ("info", "sky")):
        body = ramp(status)
        body.update({part: role(f"{status}-{part}") for part in ("solid", "soft", "border", "text", "strong")})
        colors[status] = body
        colors[remap] = ramp(status)
    for hue, hue_ramp in registry.HUE_RAMPS.items():
        colors[hue] = {str(shade): f"rgb(var(--fl-hue-{hue}-{shade}, {triplet(color)}) / <alpha-value>)"
                       for shade, color in zip(shades, hue_ramp)}
    colors.update({
        "page": role("surface-page"), "sunken": role("surface-sunken"),
        # Registry revision 3. `bg-inverse` was the surface-inverse role (ink-950) and nothing in core or the apps
        # used it; it is now the inverse fill (ink-900 unless a theme says otherwise) and the old one is `surface-inverse`.
        "inverse": role("inverse"), "on-inverse": role("on-inverse"), "surface-inverse": role("surface-inverse"),
        "accent-text": role("accent-text"), "accent-ui": role("accent-ui"), "focus": role("focus-ring"),
        "fg": role("text"), "fg-muted": role("text-muted"), "fg-subtle": role("text-subtle"),
        "line": role("border"), "line-strong": role("border-strong"),
        "primary": {"DEFAULT": role("primary"), "hover": role("primary-hover"), "soft": role("primary-soft")},
    })
    sizes = {"2xs": 10, "xs": 11, "sm": 12, "md": 13, "base": 14, "lg": 15, "xl": 16, "2xl": 17, "3xl": 26}
    font_size = {}
    for step, px in sizes.items():
        base = f"calc(var(--fl-size-{step}, {px}px) * var(--fl-size-scale, 1))"
        font_size[f"fl-{step}"] = base
        font_size[f"fl-{step}-h"] = f"calc(var(--fl-size-{step}, {px}px) * var(--fl-size-scale, 1) + 0.5px)"
    # The standard keys keep Tailwind's line heights and follow the same scale.
    for key, rem, leading in (("xs", "0.75rem", "1rem"), ("sm", "0.875rem", "1.25rem"), ("base", "1rem", "1.5rem"),
                              ("lg", "1.125rem", "1.75rem"), ("xl", "1.25rem", "1.75rem"), ("2xl", "1.5rem", "2rem")):
        font_size[key] = [f"calc({rem} * var(--fl-size-scale, 1))", {"lineHeight": leading}]
    spacing = {f"fl-{step}": f"calc(var(--fl-space-{step}, {default[f'space-{step}']}) * var(--fl-density, 1))"
               for step in registry.SPACE_STEPS}
    surface = "rgb(var(--fl-surface) / <alpha-value>)"
    on_primary = "rgb(var(--fl-on-primary) / <alpha-value>)"
    config = {
        "theme": {"extend": {
            "colors": colors,
            # `white` is the surface wherever it paints a background, line or ring, and the text on
            # the primary color wherever it paints text or a glyph; `black` text follows the mode.
            "backgroundColor": {"white": surface},
            "borderColor": {"white": surface},
            "divideColor": {"white": surface},
            "ringColor": {"white": surface},
            "ringOffsetColor": {"white": surface},
            "gradientColorStops": {"white": surface},
            "textColor": {"white": on_primary, "black": f"rgb(var(--fl-black, {triplet(registry.BLACK_LIGHT)}) / <alpha-value>)"},
            "fill": {"white": on_primary},
            "stroke": {"white": on_primary},
            "fontFamily": {
                "sans": ["var(--fl-font-sans, Inter)", "ui-sans-serif", "system-ui"],
                "mono": ["var(--fl-font-mono, ui-monospace)", "monospace"],
                "display": ["var(--fl-font-display, Inter)", "ui-sans-serif", "system-ui"],
            },
            "fontSize": font_size,
            "fontWeight": {name: f"var(--fl-weight-{name}, {default[f'weight-{name}']})"
                           for name in ("regular", "medium", "semibold", "bold")},
            "lineHeight": {f"fl-{name}": f"var(--fl-leading-{name}, {default[f'leading-{name}']})" for name in ("tight", "normal", "relaxed")},
            "letterSpacing": {f"fl-{name}": f"var(--fl-tracking-{name}, {default[f'tracking-{name}']})" for name in ("tight", "normal", "wide")},
            "spacing": spacing,
            "borderRadius": {
                "sm": f"var(--fl-radius-sm, {default['radius-sm']})",
                "DEFAULT": f"var(--fl-radius-default, {default['radius-default']})",
                "md": f"var(--fl-radius-md, {default['radius-md']})",
                "lg": "var(--fl-radius, 8px)",
                "xl": "calc(var(--fl-radius, 8px) * 1.5)",
                "2xl": "calc(var(--fl-radius, 8px) * 2)",
                "pill": f"var(--fl-radius-pill, {default['radius-pill']})",
            },
            "borderWidth": {"DEFAULT": f"var(--fl-border-width, {default['border-width']})",
                            "strong": f"var(--fl-border-width-strong, {default['border-width-strong']})"},
            "boxShadow": {name: f"var(--fl-shadow-{name}, {default[f'shadow-{name}']})"
                          for name in ("sm", "lg", "xl", "card", "popover", "modal")},
            "transitionDuration": {"DEFAULT": f"var(--fl-duration-base, {default['duration-base']})",
                                   "fast": f"var(--fl-duration-fast, {default['duration-fast']})",
                                   "base": f"var(--fl-duration-base, {default['duration-base']})"},
            "transitionTimingFunction": {"DEFAULT": f"var(--fl-ease-standard, {default['ease-standard']})"},
        }},
    }
    body = json.dumps(config, indent=2, ensure_ascii=False)
    return (f"/** {BANNER}\n"
            " *  Shared by core's tailwind.config.js and build-app.mjs: `presets: [preset]`.\n"
            " *  Every var() carries its literal default so a build made with this preset still\n"
            " *  renders on a host that predates the generated defaults. */\n"
            f"export default {body}\n")


def tokens_doc():
    out = [f"<!-- {BANNER} -->", "# Theme v2 token reference", "",
           f"Registry revision {registry.REGISTRY_REVISION}. `{{name}}` is a reference; a component token that a theme "
           "leaves unset follows its fallback live.", ""]
    for title, tokens in (("Primitives (required, literal)", registry.PRIMITIVES),
                          ("Semantic roles (required unless marked optional)", registry.SEMANTIC)):
        out += [f"## {title}", "", "| Token | Type | Default | New theme (revision 3) | Range / options |", "| --- | --- | --- | --- | --- |"]
        for t in tokens:
            fresh = registry.default_for(t)
            changed = f"`{fresh}`" if fresh != t.default else ""
            note = f"optional, since revision {t.since}; " if t.optional else ""
            out.append(f"| `{t.name}` | {t.type} | `{t.default}` | {changed} | {note}{limits(t)} |")
        out.append("")
    out += ["`Default` is the generated CSS fallback and what revisions 1 and 2 start a theme from; it never changes. "
            "`New theme` is what a theme that targets revision 3 starts from (`default_theme_v2`, the Themes editor and the builder).", ""]
    out += ["## Component tokens (optional)", ""]
    for key, label in registry.COMPONENTS.items():
        out += [f"### {label} (`{key}`)", "", "| Token | Type | Fallback | Range / options |", "| --- | --- | --- | --- |"]
        for t in registry.COMPONENT_TOKENS:
            if t.component == key:
                default = " / ".join(f"{k}: `{v}`" for k, v in t.default.items()) if isinstance(t.default, dict) else f"`{t.default}`"
                out.append(f"| `{t.name}` | {t.type} | {default} | {limits(t)} |")
        out.append("")
    out += ["## Dark mode (registry revision 2)", "",
            "`color_scheme` is `light`, `dark` or `auto` (revision 1 allows `light` only). A `dark` theme's own tokens are a dark palette. "
            "An `auto` theme's tokens are its light palette and `modes.dark` overrides them; the user picks light, dark or the system's.", "",
            f"`modes.dark` must set every colour ramp ({', '.join(registry.COLOR_RAMPS)}; {len(registry.DARK_REQUIRED) - 2} tokens), `surface` and `on-primary`. "
            "It may also override any of these (everything else is the same in both modes):", "",
            ", ".join(f"`{name}`" for name in registry.MODE_TOKENS if name not in registry.DARK_REQUIRED), ""]
    out += ["## Layout", "", "| Field | Values | Default |", "| --- | --- | --- |"]
    for key, spec in registry.LAYOUT_SPEC.items():
        if "type" in spec:
            out.append(f"| `layout.{key}` | {layout_values(spec)} | `{spec['default']}` |")
        else:
            for name, field in spec.items():
                out.append(f"| `layout.{key}.{name}` | {layout_values(field)} | `{field['default']}` |")
    out += ["", "## Contrast", "",
            "A theme is judged only against the pairs of the registry revision it targets. `ui` pairs are the colours the interface "
            "paints with (a raw ramp step, `text-white` on a dark fill); they are reported apart from the role pairs. "
            "A pair marked *unless* is not judged for a theme that sets that role: the role replaces the raw step.", "",
            "| Pair | Minimum | Level | Since | Group | Unless |", "| --- | --- | --- | --- | --- | --- |"]
    for p in registry.CONTRAST_PAIRS:
        out.append(f"| `{p.fg}` on `{p.bg}` | {p.min:g}:1 | {p.level} | {p.since} | {p.group} | {('`' + p.unless + '` set') if p.unless else ''} |")
    for bar, tone, bg in registry.NAV_BARS:
        out.append(f"| `nav-item-fg` on `{bg}` (by `{tone}`) | 4.5:1 | error |")
    return "\n".join(out) + "\n"


def limits(token):
    if token.options:
        return ", ".join(token.options)
    if token.min is not None or token.max is not None:
        return f"{'' if token.min is None else token.min:g} to {'' if token.max is None else token.max:g}"
    return ""


def layout_values(field):
    if field["type"] in ("enum", "step"):
        return ", ".join(field["options"])
    if field["type"] == "int":
        return ("0 or " if field.get("zero") else "") + f"{field['min']}-{field['max']}"
    return "true, false"


def default_release():
    """The platform default theme: fastlane 2.0.0, the registry's revision 3 palette as a v2 manifest."""
    return json.dumps(themes.default_theme_v2("fastlane", "2.0.0", "Fastlane"), indent=2, sort_keys=True) + "\n"


def outputs():
    registry_json = json.dumps(registry.registry_json(), indent=2, ensure_ascii=False) + "\n"
    return {
        ROOT / "fastlanelabs_sdk/registry_data/theme-registry-v2.json": registry_json,
        ROOT / "fastlanelabs_sdk/registry_data/default-theme-v2.json": default_release(),
        ROOT / "frontend/theme-registry.json": registry_json,
        ROOT / "frontend/theme-defaults.css": defaults_css(),
        ROOT / "frontend/tailwind-preset.mjs": preset(),
        ROOT / "docs/theme-v2-tokens.md": tokens_doc(),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if a generated file is out of date")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Out of date; run scripts/gen_theme_registry.py:", *stale, sep="\n  ")
        sys.exit(1)


if __name__ == "__main__":
    main()
